users = {
    "admin": "admin",
    "testuser": "123",
    "john_doe": "password123",
    "alice_wonderland": "w0nd3rL@nd",
    "tech_guru_42": "PythonRocks",
    "coding_ninja": "SecretCode",
    "user123": "p@ssw0rd",
    "web_dev_master": "HTML_CSS_JS",
    "security_expert": "SecureMeNow",
    "data_scientist": "BigData123",
    "robotics_enthusiast": "RoboWorld",
    "game_master_88": "G@meOn!",
    "coffee_lover": "C0ffeeTime",
    "music_maniac": "Melody123",
    "bookworm_42": "ReadBooks",
    "adventure_seeker": "Explore123",
    "design_guru": "Creativity123",
    "artistic_soul": "Painting@Heart",
    "traveller_007": "Wanderlust",
    "coding_is_fun": "FunWithCode",
}